def author_json_result
  {
  "status" => "OK",
  "usage" => "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url" => "http://techcrunch.com/2016/01/29/ibm-watson-weather-company-sale/",
  "authors" => {
    "names" => [
      "Author Name 1",
      "Author Name 2"
    ]
    }
  }
end

def author_api_result
  {
  "status": "OK",
  "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url": "http://techcrunch.com/2016/01/29/ibm-watson-weather-company-sale/",
  "authors": {
    "names": [
      "Author Name 1",
      "Author Name 2"
    ]
    }
  }
end

# "https://gateway-a.watsonplatform.net/calls/url=https://www.ibm.com/us-en/URLGetCombinedData?apikey=asdas"